server:
    error:
        include-message: always
        include-binding-errors: always

spring:
    http:
        encoding:
            enabled: true
            charset: UTF-8
            force: true

        multipart:
            enabled: true
    servlet:
        multipart:
            max-file-size: 8MB
            max-request-size: 8MB
    datasource:
        url: YOUR_DB_URL
        username: YOUR_DB_USERNAME
        password: YOUR_DB_PASS
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
rsa:
    private-key: "classpath:certs/private.pem"
    public-key: "classpath:certs/public.pem"

jwt:
    expiration:
        time: 900000

custom:
    backend:
        address: YOUR_BACKEND_ADDRESS